---
date: "2016-12-30T21:49:57-07:00"
title: conferences and websites
---

# why I need a website

In early August I submitted an abstract titled: *"Online interactive dashboards, reporting apps and query  portals for TVET Colleges"*  to a [conference](<http://northsouthconference.co.za>) in Cape Town and not long afterward was informed that I was selected to present my topic.  
I was happy and thankful. I spent many, many hours building an example Shiny dashboard app plus a dynamically-linked report in the hope that I would make a favourable impression, and that at least one college would call to ask for assistance.
  
Well, the day arrived. I was assigned the 'graveyard' slot, the final presentation of the day. Exhausted delegates keen to end the day with a Martini or head out early to avoid the nightmarish traffic lanes that snake out of the city shuffled into the room. Naturally, by the time I started the internet connectivity was down so no chance of getting them to give the hosted apps a test-run. Confronted with 'zombie-like' stares I soldiered to the end.  
I handed over 2 business cards - one to a delegate from the Eastern Cape, another to a sympathetic man from Gauteng.  
  
I grabbed my 'presenter's gift', hurried to a conference administrator to have my parking validated and walked out of the hotel to join the long snaking lines of traffic out of the city. Job well done.  
  
When I finally arrived home I decided that it makes perfect sense to build my website. I needed a more efficient strategy to communicate with the world.

